$(document).ready(function() {
  var tropes = [
    "alchemists",
    "aliens",
    "amazons",
    "ancient/lost technology",
    "angels",
    "archaeologists",
    "artificial intelligence",
    "assassins",
    "astrologers/fortune tellers",
    "astronomers",
    "Atlantis",
    "Aztecs",
    "beggars",
    "bootleggers",
    "bounty hunters",
    "brothels",
    "butlers",
    "casinos",
    "castles",
    "catacombs",
    "catburglars",
    "centaurs",
    "clones",
    "clowns",
    "con artists",
    "cowboys",
    "crazy scientists",
    "cyberpunk",
    "cyborgs",
    "demons",
    "detectives",
    "dieselpunk",
    "dinosaurs",
    "disembodied voices",
    "dragons",
    "drugs",
    "eldritch abominations",
    "evil trees",
    "explorers",
    "faeries",
    "factories/plants",
    "flamencos",
    "flamingos",
    "floating cities",
    "Four Horsemen",
    "gangsters",
    "genetics/geneticists",
    "genies",
    "ghost hunters",
    "giant apes",
    "giants",
    "goblins",
    "golemancers",
    "gun priests",
    "gunslingers",
    "hackers",
    "heaven and hell",
    "hive minds",
    "hospitals",
    "hot air balloons",
    "Igors",
    "Illuminati",
    "Jedi and Sith",
    "journalists",
    "kitty cats and puppy dogs",
    "krakens",
    "kung fu masters",
    "lawyers",
    "leather",
    "libraries",
    "liches",
    "lions, tigers, and bears",
    "lizardfolk/saurians",
    "mad gods",
    "magepunk",
    "magitech",
    "malls",
    "masquerade balls",
    "mechanics",
    "mechs",
    "meteorite metal",
    "militaries",
    "minotaurs",
    "money laundering",
    "mountain men",
    "motorcycles",
    "mummies",
    "musicians",
    "mutants",
    "mysterious orbs",
    "necromancers",
    "nephilim",
    "ninjas",
    "nuclear energy/weapons",
    "old gods",
    "orphans",
    "pandas",
    "pirates",
    "planeswalkers",
    "poachers",
    "policemen",
    "prophecies",
    "prostitutes",
    "psions and psychics",
    "pyramids and pharaohs",
    "rat-men",
    "robots",
    "royalty",
    "rune magic",
    "samurais",
    "sasquatch",
    "secret societies",
    "shamans and witch doctors",
    "skyscrapers and sky bridges",
    "slaves",
    "smugglers",
    "space battles",
    "Spartans",
    "sphinxes",
    "spies",
    "starships",
    "steampunk",
    "street racers",
    "submarines",
    "super soldiers",
    "supercorporations",
    "superheroes",
    "swashbucklers",
    "tanks",
    "tattoos",
    "titans",
    "trolls",
    "twins/triplets",
    "vampires",
    "vikings",
    "viruses and epidemics",
    "viziers",
    "warlords",
    "werewolves",
    "wild gods",
    "yetis",
    "Zeppelins",
    "zombies",
    "zoos/menageries"
  ];
  // console.log("tropes length: " + tropes.length);

  $('#generate').click(function() {
    var these_ones = [];
    $('#generated').empty();
    var i=0;
    do {
      var this_one = tropes[Math.floor(Math.random()*tropes.length)];
      if (!these_ones.includes(this_one)) {
        $('#generated').append(this_one).append("<br />");
        these_ones[i++] = this_one;
      }
    } while (i<3);
  });

});
